name: Cypress run
on:
  workflow_dispatch:
env:
  CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Get project code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i --force
      - name: Run server and test
        run: npm run cy:run
