name: Hillel Auto e2e tests
on: workflow_dispatch

jobs:
  cypress_run:
    runs-on: ubuntu-22.04
    steps:
      - name: Get project files
        uses: actions/checkout@v4
      - name: Install all dependencies
        run: npm install
      - name: Run tests
        run: npm run cy:run
